version: '3.8'

services:
  load_balancer:
    build: ./load_balancer
    ports:
      - "5000:5000"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - lbnet

  server1:
    build: ./server
    environment:
      - SERVER_ID=1
    networks:
      - lbnet

  server2:
    build: ./server
    environment:
      - SERVER_ID=2
    networks:
      - lbnet

  server3:
    build: ./server
    environment:
      - SERVER_ID=3
    networks:
      - lbnet

networks:
  lbnet:
